{% set org = "analyst-collective" %}
{% set name = "dbt" %}
{% set version = "0.6.2" %}
{% set sha256 = "2f5242713e85f8c1d6cb8162f004127dfc46d342366b9f014a2834d106984559" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/{{ org }}/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - dbt
    - tests

about:
  home: https://github.com/analyst-collective/dbt
  license: Apache-2.0
  license_file: License.md
  summary: 'dbt helps analysts write reliable, modular code using a workflow that closely mirrors software development.'

  description: |
    dbt (data build tool) helps analysts write reliable, modular code
    using a workflow that closely mirrors software development. Used
    by individuals and teams alike, dbt is an analytics tool for
    perfectionists with deadlines.
  doc_url: http://dbt.readthedocs.io/en/master/
  dev_url: https://github.com/analyst-collective/dbt

extra:
  recipe-maintainers:
    - drewbanin
    - jthandy
